#!/usr/bin/env bash
# a Bash script that install nginx on server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page that contains
# the string Hello World!
sudo apt-get -y update
sudo apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
