#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo service haproxy start
sed -i "$ a ENABLED=1" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sed -i "$ a frontend http\n\tbind *:80\n\tdefault_backend webservers\nbackend webservers\n\tserver 173886-web-01 18.209.224.9:80 check\n\tserver 173886-web-02 34.232.72.45:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
