#!/usr/bin/env bash
"""
This script installs Nginx, Configure Nginx to listen on port 80 and allow incoming
traffic on port 80, then start nginx
"""
st="\tlisten 8080 default_server\;"
newst="\tlisten 80 default_server\;"
st2="\tlisten \[::\]:8080 default_server"
newst2="\tlisten \[::\]:80 default_server"
sudo sed -i "0,/$st/{s/$st/$newst/}" /etc/nginx/sites-enabled/default
sudo sed -i "0,/$st2/{s/$st2/$newst2/}" /etc/nginx/sites-enabled/default
sudo service nginx start
