#!/usr/bin/env bash
# makes nginx run as user nginx
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo su nginx -c "service nginx start"
